name: affinidi_tdk_dart

packages:
  - packages/**

scripts:
  test:
    run: |
      melos run execute-tests
      melos run coverage-report

  execute-tests:
    run: |
      if [ -d "test" ]; then 
        if [ -f "pubspec.yaml" ] && grep -q "sdk: flutter" pubspec.yaml; then
          flutter test --coverage
        else
          dart run coverage:test_with_coverage
        fi
      else
        echo "No tests in $(pwd), skipping."
      fi
    description: Run tests in each package
    exec:
      concurrency: 4
      failFast: true
  
  coverage-report:
    run: |
      mkdir -p coverage
      find ./packages -name "lcov.info" -path "*/coverage/lcov.info" -exec cat {} + > coverage/lcov.info