name: affinidi_tdk_dart
description: Dart Packages for Affinidi TDK
publish_to: none
environment:
  sdk: ^3.8.0
workspace:
  - packages/auth_provider
  - packages/claim_verifiable_credential
  - packages/common
  - packages/consumer_auth_provider
  - packages/cryptography
  - packages/iota_core
  - packages/test_utilities
  - packages/vault
  - packages/vault_data_manager
  - packages/vault_flutter_utils
  - packages/vault_flutter_utils/example/flutter_secure_storage
  - packages/integration_tests
  - clients/login_configuration_client
  - clients/credential_issuance_client
  - clients/iam_client
  - clients/credential_verification_client
  - clients/wallets_client
  - clients/iota_client
  - clients/vault_data_manager_client
dev_dependencies:
  coverage: ^1.11.1
  dart_flutter_team_lints: ^3.2.1
  melos: ^7.0.0-dev.9
  test: ^1.24.0
melos:
  scripts:
    analyze:
      exec: dart analyze .
      concurrency: 4
      failFast: true
      noSelect: true
      packageFilters:
        flutter: true
        includePrivatePackages: false
        diff: origin/main
    test:
      run: |
        melos run test-flutter
        melos run test-dart
        melos run coverage-report
    test-flutter:
      description: Run tests in each flutter package
      exec: flutter test --coverage
      dirExists: test
      concurrency: 4
      failFast: true
      noSelect: true
      packageFilters:
        flutter: true
        includePrivatePackages: false
        diff: origin/main
        ignore:
          - "*_example*"
    test-dart:
      description: Run tests in each dart package
      exec: dart run coverage:test_with_coverage
      dirExists: test
      concurrency: 4
      failFast: true
      noSelect: true
      packageFilters:
        flutter: false
        private: false
        diff: origin/main
        ignore:
          - "*_example*"
    test-integration:
      description: Run integration tests
      exec: dart test
      dirExists: test
      concurrency: 4
      failFast: true
      noSelect: true
      packageFilters:
        flutter: false
        private: true
        scope:
          - "*integration_tests*"
    coverage-report:
      run: >
        mkdir -p coverage

        find ./packages -name "lcov.info" -path "*/coverage/lcov.info" -exec cat
        {} + > coverage/lcov.info
