name: affinidi_tdk_dart
description: Dart Packages for Affinidi TDK
publish_to: none
environment:
  sdk: ^3.8.0
workspace:
  - packages/auth_provider
  - packages/claim_verifiable_credential
  - packages/common
  - packages/consumer_auth_provider
  - packages/cryptography
  - packages/iota_core
  - packages/test_utilities
  - packages/vault
  - packages/vault_data_manager
  - packages/vault_flutter_utils
  - packages/vault_flutter_utils/example/flutter_secure_storage
  - packages/integration_tests
  - clients/login_configuration_client
  - clients/credential_issuance_client
  - clients/iam_client
  - clients/credential_verification_client
  - clients/wallets_client
  - clients/iota_client
  - clients/vault_data_manager_client
  - packages/vault_edge_drift_provider
  - packages/vault_edge_provider
  - packages/didcomm/didcomm_mediator_client
  - packages/didcomm/vdsp
  - packages/didcomm/vdip
  - packages/common/example
  - packages/consumer_auth_provider/example
  - packages/vault/example
  - clients/dart/login_configuration_client
  - clients/dart/vault_data_manager_client
  - clients/dart/credential_verification_client
  - clients/dart/iam_client
  - clients/dart/wallets_client
  - clients/dart/credential_issuance_client
  - clients/dart/consumer_iam_client
  - clients/dart/iota_client
dev_dependencies:
  coverage: ^1.11.1
  dart_flutter_team_lints: ^3.2.1
  melos: ^7.0.0-dev.9
  test: ^1.24.0
melos:
  scripts:
    fix:
      exec: dart fix --apply
      concurrency: 4
      failFast: true
      noSelect: true
      packageFilters:
        includePrivatePackages: false
        diff: origin/main
    analyze:
      exec: dart analyze .
      concurrency: 4
      failFast: true
      noSelect: true
      packageFilters:
        flutter: true
        includePrivatePackages: false
        diff: origin/main
    test:
      run: |
        melos run test-flutter
        melos run test-dart
        melos run coverage-report
    test-flutter:
      description: Run tests in each flutter package
      exec: flutter test --coverage
      dirExists: test
      concurrency: 4
      failFast: true
      noSelect: true
      packageFilters:
        flutter: true
        includePrivatePackages: false
        diff: origin/main
        ignore:
          - "*_example*"
    test-dart:
      description: Run tests in each dart package
      exec: dart run coverage:test_with_coverage
      dirExists: test
      concurrency: 4
      failFast: true
      noSelect: true
      packageFilters:
        flutter: false
        private: false
        diff: origin/main
        ignore:
          - "*_example*"
    test-integration:
      description: Run integration tests
      run: ./scripts/test-integration.sh
      dirExists: test
      concurrency: 4
      failFast: true
      noSelect: true
      packageFilters:
        flutter: false
        private: true
        scope:
          - "*integration_tests*"
    coverage-report:
      run: ./scripts/coverage-report.sh
