name: common_example
description: Affinidi TDK Common package example
version: 2.0.0
publish_to: none

environment:
  sdk: ^3.8.0

resolution: workspace

dependencies:
  affinidi_tdk_common: ^2.0.0
  affinidi_tdk_credential_issuance_client: ^2.0.0
  affinidi_tdk_iota_client: ^2.0.0
dev_dependencies:
  affinidi_tdk_auth_provider: any
