name: affinidi_tdk_auth_provider
description: Auth provider that allows creating project scoped tokens to access Affinidi services
version: 2.0.1
repository: https://github.com/affinidi/affinidi-tdk-dart
environment:
  sdk: ^3.8.0
resolution: workspace
dependencies:
  affinidi_tdk_common: ^2.0.0
  asn1lib: ^1.5.9
  dart_jsonwebtoken: ^3.2.0
  http: ^1.1.0
  pointycastle: ^4.0.0
  uuid: ^4.5.1
dev_dependencies:
  dotenv: ^4.2.0
  lints: ^5.0.0
  mocktail: ^1.0.4
  path: ^1.9.0
  test: ^1.24.0