name: vault_example
description: Vault Example
version: 2.0.0
publish_to: none

environment:
  sdk: ^3.8.0

resolution: workspace

dependencies:
  affinidi_tdk_vault: ^2.1.0
  affinidi_tdk_vault_data_manager: ^2.0.2
  base_codecs: ^1.0.1
  ssi: ^3.3.0

dev_dependencies:
  test: ^1.24.0
