name: consumer_auth_provider_example
version: 2.0.0
publish_to: none

environment:
  sdk: ^3.8.0

resolution: workspace

dependencies:
  affinidi_tdk_consumer_auth_provider: ^5.0.0
  base_codecs: ^1.0.1
  ssi: ^3.3.0
