name: Pull Request Checks

on: 
  pull_request:
     
jobs:
  dart-pipeline:
    uses: affinidi/pipeline-dart/.github/workflows/check.yaml@feat/add-integration-tests-workflow
    secrets: inherit
    with:
      flutter-version: '3.32.4'