name: Integration Tests

on:
  pull_request:

jobs:
  dart-pipeline:
    uses: affinidi/pipeline-dart/.github/workflows/integration-tests.yaml@main
    secrets: inherit
    with:
      flutter-version: '3.32.4'
      working-directory: './packages/integration_tests'