name: Integration Tests

on:
  pull_request:

jobs:
  dart-pipeline:
    uses: affinidi/pipeline-dart/.github/workflows/check.yaml@feat/add-integration-tests-workflow
    secrets: inherit
    with:
      dart-version: '3.8.1'
      working-directory: './packages/integration_tests'